"""add rejete_par to medecin

Revision ID: 23ce3c55b54a
Revises: bb2eba2f7ca6
Create Date: 2026-06-16 19:38:56.863627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ce3c55b54a'
down_revision: Union[str, None] = 'bb2eba2f7ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: les changements détectés sur la table 'commentaires' (parent_id,
    # auteur_type, auteur_aide_id, likes_count, nullabilité de auteur_id) sont
    # un chantier séparé non lié à ce correctif et ont été retirés volontairement
    # de cette migration pour éviter un ALTER TABLE NOT NULL risqué sans défaut.
    op.add_column('medecins', sa.Column('rejete_par', sa.String(length=15), nullable=True))
    op.create_foreign_key(None, 'medecins', 'admins', ['rejete_par'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medecins', type_='foreignkey')
    op.drop_column('medecins', 'rejete_par')
    # ### end Alembic commands ###
