"""add_patient_fields

Revision ID: 9487a644c3b9
Revises: a1b2c3d4e5f6
Create Date: 2026-05-30 11:01:36.507674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9487a644c3b9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_acces_demandeur'), table_name='acces_patient')
    op.drop_index(op.f('idx_acces_proprietaire'), table_name='acces_patient')
    op.drop_index(op.f('idx_acces_statut'), table_name='acces_patient')
    op.drop_table_comment(
        'acces_patient',
        existing_comment="Demandes d'accÃ¨s inter-mÃ©decins aux dossiers patients",
        schema=None
    )
    op.drop_column('acces_patient', 'date_expiration')
    op.drop_column('acces_patient', 'peut_modifier')
    op.drop_table_comment(
        'admins',
        existing_comment='Administrateurs de la plateforme PneumoIA',
        schema=None
    )
    op.drop_index(op.f('idx_audit_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_created'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_medecin'), table_name='audit_logs')
    op.drop_table_comment(
        'audit_logs',
        existing_comment="Journal d'audit des actions utilisateur",
        schema=None
    )
    op.drop_index(op.f('idx_cas_created'), table_name='cas_cliniques_publics')
    op.drop_index(op.f('idx_cas_pathologie'), table_name='cas_cliniques_publics')
    op.drop_table_comment(
        'cas_cliniques_publics',
        existing_comment='Cas cliniques publics affichÃ©s sur la landing page',
        schema=None
    )
    op.drop_index(op.f('idx_comment_publication'), table_name='commentaires')
    op.drop_table_comment(
        'commentaires',
        existing_comment='Commentaires sur les publications',
        schema=None
    )
    op.drop_index(op.f('idx_communautes_createur'), table_name='communautes')
    op.drop_index(op.f('idx_communautes_type'), table_name='communautes')
    op.drop_table_comment(
        'communautes',
        existing_comment='CommunautÃ©s mÃ©dicales de partage de cas cliniques',
        schema=None
    )
    op.add_column('consultations', sa.Column('antecedents_consultation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('consultations', sa.Column('observations', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_consult_created'), table_name='consultations')
    op.drop_index(op.f('idx_consult_medecin'), table_name='consultations')
    op.drop_index(op.f('idx_consult_patient'), table_name='consultations')
    op.drop_index(op.f('idx_consult_statut'), table_name='consultations')
    op.drop_table_comment(
        'consultations',
        existing_comment='Consultations mÃ©dicales avec symptÃ´mes et avis',
        schema=None
    )
    op.drop_index(op.f('idx_diag_consultation'), table_name='diagnostics_ia')
    op.drop_table_comment(
        'diagnostics_ia',
        existing_comment="RÃ©sultats de l'analyse IA pour chaque consultation",
        schema=None
    )
    op.drop_index(op.f('idx_docs_medecin'), table_name='documents_medecin')
    op.drop_table_comment(
        'documents_medecin',
        existing_comment="Documents justificatifs uploadÃ©s lors de l'inscription",
        schema=None
    )
    op.drop_index(op.f('idx_feedback_diagnostic'), table_name='feedbacks_ia')
    op.drop_index(op.f('idx_feedback_medecin'), table_name='feedbacks_ia')
    op.drop_table_comment(
        'feedbacks_ia',
        existing_comment='Retour du mÃ©decin sur la pertinence du diagnostic IA',
        schema=None
    )
    op.drop_index(op.f('idx_medecins_email'), table_name='medecins')
    op.drop_index(op.f('idx_medecins_statut'), table_name='medecins')
    op.drop_table_comment(
        'medecins',
        existing_comment='MÃ©decins inscrits â€” ID format PNEU-XXXXXXX',
        schema=None
    )
    op.drop_index(op.f('idx_membres_medecin'), table_name='membres_communaute')
    op.drop_table_comment(
        'membres_communaute',
        existing_comment='Appartenance des mÃ©decins aux communautÃ©s',
        schema=None
    )
    op.drop_index(op.f('idx_notif_created'), table_name='notifications')
    op.drop_index(op.f('idx_notif_destinataire'), table_name='notifications')
    op.drop_table_comment(
        'notifications',
        existing_comment='Notifications in-app pour mÃ©decins et admins',
        schema=None
    )
    op.drop_index(op.f('idx_otp_expires'), table_name='otp_codes')
    op.drop_index(op.f('idx_otp_medecin'), table_name='otp_codes')
    op.drop_table_comment(
        'otp_codes',
        existing_comment='Codes OTP 6 chiffres pour la double authentification',
        schema=None
    )
    op.add_column('patients', sa.Column('civilite', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('adresse', sa.String(length=300), nullable=True))
    op.add_column('patients', sa.Column('profession', sa.String(length=150), nullable=True))
    op.add_column('patients', sa.Column('personne_a_contacter', sa.String(length=150), nullable=True))
    op.add_column('patients', sa.Column('telephone_urgence', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_patients_created_by'), table_name='patients')
    op.drop_index(op.f('idx_patients_nom_prenom'), table_name='patients')
    op.drop_table_comment(
        'patients',
        existing_comment='Dossiers patients crÃ©Ã©s par les mÃ©decins',
        schema=None
    )
    op.drop_index(op.f('idx_pub_auteur'), table_name='publications')
    op.drop_index(op.f('idx_pub_communaute'), table_name='publications')
    op.drop_index(op.f('idx_pub_created'), table_name='publications')
    op.drop_index(op.f('idx_pub_type'), table_name='publications')
    op.drop_table_comment(
        'publications',
        existing_comment='Publications dans les communautÃ©s',
        schema=None
    )
    op.drop_table_comment(
        'reactions',
        existing_comment='RÃ©actions aux publications',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'reactions',
        'RÃ©actions aux publications',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'publications',
        'Publications dans les communautÃ©s',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_pub_type'), 'publications', ['type'], unique=False)
    op.create_index(op.f('idx_pub_created'), 'publications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_pub_communaute'), 'publications', ['communaute_id'], unique=False)
    op.create_index(op.f('idx_pub_auteur'), 'publications', ['auteur_id'], unique=False)
    op.create_table_comment(
        'patients',
        'Dossiers patients crÃ©Ã©s par les mÃ©decins',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_patients_nom_prenom'), 'patients', ['nom', 'prenom'], unique=False)
    op.create_index(op.f('idx_patients_created_by'), 'patients', ['created_by'], unique=False)
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'telephone_urgence')
    op.drop_column('patients', 'personne_a_contacter')
    op.drop_column('patients', 'profession')
    op.drop_column('patients', 'adresse')
    op.drop_column('patients', 'civilite')
    op.create_table_comment(
        'otp_codes',
        'Codes OTP 6 chiffres pour la double authentification',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_otp_medecin'), 'otp_codes', ['medecin_id'], unique=False)
    op.create_index(op.f('idx_otp_expires'), 'otp_codes', ['expires_at'], unique=False)
    op.create_table_comment(
        'notifications',
        'Notifications in-app pour mÃ©decins et admins',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_notif_destinataire'), 'notifications', ['destinataire_id', 'lu'], unique=False)
    op.create_index(op.f('idx_notif_created'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table_comment(
        'membres_communaute',
        'Appartenance des mÃ©decins aux communautÃ©s',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_membres_medecin'), 'membres_communaute', ['medecin_id'], unique=False)
    op.create_table_comment(
        'medecins',
        'MÃ©decins inscrits â€” ID format PNEU-XXXXXXX',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_medecins_statut'), 'medecins', ['statut'], unique=False)
    op.create_index(op.f('idx_medecins_email'), 'medecins', ['email'], unique=False)
    op.create_table_comment(
        'feedbacks_ia',
        'Retour du mÃ©decin sur la pertinence du diagnostic IA',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_feedback_medecin'), 'feedbacks_ia', ['medecin_id'], unique=False)
    op.create_index(op.f('idx_feedback_diagnostic'), 'feedbacks_ia', ['diagnostic_id'], unique=False)
    op.create_table_comment(
        'documents_medecin',
        "Documents justificatifs uploadÃ©s lors de l'inscription",
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_docs_medecin'), 'documents_medecin', ['medecin_id'], unique=False)
    op.create_table_comment(
        'diagnostics_ia',
        "RÃ©sultats de l'analyse IA pour chaque consultation",
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_diag_consultation'), 'diagnostics_ia', ['consultation_id'], unique=False)
    op.create_table_comment(
        'consultations',
        'Consultations mÃ©dicales avec symptÃ´mes et avis',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_consult_statut'), 'consultations', ['statut'], unique=False)
    op.create_index(op.f('idx_consult_patient'), 'consultations', ['patient_id'], unique=False)
    op.create_index(op.f('idx_consult_medecin'), 'consultations', ['medecin_id'], unique=False)
    op.create_index(op.f('idx_consult_created'), 'consultations', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('consultations', 'observations')
    op.drop_column('consultations', 'antecedents_consultation')
    op.create_table_comment(
        'communautes',
        'CommunautÃ©s mÃ©dicales de partage de cas cliniques',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_communautes_type'), 'communautes', ['type'], unique=False)
    op.create_index(op.f('idx_communautes_createur'), 'communautes', ['createur_id'], unique=False)
    op.create_table_comment(
        'commentaires',
        'Commentaires sur les publications',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_comment_publication'), 'commentaires', ['publication_id'], unique=False)
    op.create_table_comment(
        'cas_cliniques_publics',
        'Cas cliniques publics affichÃ©s sur la landing page',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_cas_pathologie'), 'cas_cliniques_publics', ['pathologie'], unique=False)
    op.create_index(op.f('idx_cas_created'), 'cas_cliniques_publics', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table_comment(
        'audit_logs',
        "Journal d'audit des actions utilisateur",
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_audit_medecin'), 'audit_logs', ['medecin_id'], unique=False)
    op.create_index(op.f('idx_audit_created'), 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_logs', ['action'], unique=False)
    op.create_table_comment(
        'admins',
        'Administrateurs de la plateforme PneumoIA',
        existing_comment=None,
        schema=None
    )
    op.add_column('acces_patient', sa.Column('peut_modifier', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('acces_patient', sa.Column('date_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'acces_patient',
        "Demandes d'accÃ¨s inter-mÃ©decins aux dossiers patients",
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_acces_statut'), 'acces_patient', ['statut'], unique=False)
    op.create_index(op.f('idx_acces_proprietaire'), 'acces_patient', ['medecin_proprietaire_id'], unique=False)
    op.create_index(op.f('idx_acces_demandeur'), 'acces_patient', ['medecin_demandeur_id'], unique=False)
    # ### end Alembic commands ###
