"""add updated_at to medecin

Revision ID: bb2eba2f7ca6
Revises: e164e3ccd219
Create Date: 2026-06-16 19:26:26.131301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2eba2f7ca6'
down_revision: Union[str, None] = 'e164e3ccd219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: les changements détectés sur la table 'commentaires' (parent_id,
    # auteur_type, auteur_aide_id, likes_count, nullabilité de auteur_id) sont
    # un chantier séparé non lié à ce correctif et ont été retirés volontairement
    # de cette migration pour éviter un ALTER TABLE NOT NULL risqué sans défaut.
    op.add_column('medecins', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medecins', 'updated_at')
    # ### end Alembic commands ###
