"""add suspension corbeille relance fields to medecin

Revision ID: e164e3ccd219
Revises: 33368a2467f1
Create Date: 2026-06-16 15:54:38.874916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e164e3ccd219'
down_revision: Union[str, None] = '33368a2467f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: les changements détectés sur la table 'commentaires' (parent_id,
    # auteur_type, auteur_aide_id, likes_count, nullabilité de auteur_id) sont
    # un chantier séparé non lié à ce correctif et ont été retirés volontairement
    # de cette migration pour éviter un ALTER TABLE NOT NULL risqué sans défaut.
    op.add_column('medecins', sa.Column('suspension_raison', sa.Text(), nullable=True))
    op.add_column('medecins', sa.Column('suspension_duree', sa.String(length=50), nullable=True))
    op.add_column('medecins', sa.Column('suspension_par', sa.String(length=15), nullable=True))
    op.add_column('medecins', sa.Column('suspension_le', sa.DateTime(), nullable=True))
    op.add_column('medecins', sa.Column('statut_precedent', sa.String(length=20), nullable=True))
    op.add_column('medecins', sa.Column('supprime_le', sa.DateTime(), nullable=True))
    op.add_column('medecins', sa.Column('supprime_par', sa.String(length=15), nullable=True))
    op.add_column('medecins', sa.Column('relance_sent', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('medecins', sa.Column('relance_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'medecins', 'admins', ['suspension_par'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'medecins', 'admins', ['supprime_par'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medecins', type_='foreignkey')
    op.drop_constraint(None, 'medecins', type_='foreignkey')
    op.drop_column('medecins', 'relance_at')
    op.drop_column('medecins', 'relance_sent')
    op.drop_column('medecins', 'supprime_par')
    op.drop_column('medecins', 'supprime_le')
    op.drop_column('medecins', 'statut_precedent')
    op.drop_column('medecins', 'suspension_le')
    op.drop_column('medecins', 'suspension_par')
    op.drop_column('medecins', 'suspension_duree')
    op.drop_column('medecins', 'suspension_raison')
    # ### end Alembic commands ###
